# Generated by Django 4.0.2 on 2022-03-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Lang'), (1, 'Tool'), (2, 'Framework'), (3, 'Environment')], default='SKILL_CATEGORY_TOOL')),
            ],
            options={
                'verbose_name': 'skill_category',
                'verbose_name_plural': 'skill_categories',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycv.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_till', models.DateField()),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(related_name='resume_items', to='mycv.Skill')),
            ],
        ),
    ]
